### ISSUE TITLE
API Keys Exposed!

### ISSUE THREAD

**Issue by heyadityak** [tanmayrajani/markdown-editor#1]
Hi @tanmayrajani there's a small security issue. The API Keys for GitHub are exposed in your server file (`index.js`). Please resolve this 😃

**Comment by tanmayrajani** [comment]
Oh yes :smile: I didn't care earlier because this was a private repository and been moved to public later. Keys remain in commit history though :laughing: 

Thanks for bringing it up anyway :clinking_glasses:
